version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_data
