"""migration

Revision ID: 0e096b3ae7b4
Revises: 
Create Date: 2021-07-08 15:06:21.117210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e096b3ae7b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruit',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fruit')
    # ### end Alembic commands ###
